### ISSUE TITLE
Instalación y documentación de Visual Studio Community

### ISSUE THREAD

**Issue by jaquelineordonez** [jaquelineordonez/Sistema-para-administrar-respaldos#2]

**Comment by jaquelineordonez** [comment]
[proceso para instalar Visual Studio.docx](https://github.com/jaquelineordonez/Sistema-para-administrar-respaldos/files/714416/proceso.para.instalar.Visual.Studio.docx)

**Comment by AlonsoMeraz** [comment]
1. Describir cuales son las diferencias entre la versión community que se está usando y otras versiones de paga que existen.
2. Cambiar la redacción para que las frases queden descritas en tercera persona, evitando tutear al lector.

**Comment by jaquelineordonez** [comment]
1. Se complemento la parte de introducción describiendo la diferencia que existe entre el Visual Studio community y sus demás versiones.
2. Se modifico la redacción quedando el texto descrito en tercera persona.
[proceso para instalar Visual Studio OK.docx](https://github.com/jaquelineordonez/Sistema-para-administrar-respaldos/files/720172/proceso.para.instalar.Visual.Studio.OK.docx)
